CREATE TABLE "DB2INST1"."MPRODCHG"  (
		  "PRDCD" VARCHAR(2) NOT NULL WITH DEFAULT '' , 
		  "SWIFTCD" VARCHAR(3) NOT NULL WITH DEFAULT '' , 
		  "BNDCD" VARCHAR(3) NOT NULL WITH DEFAULT '' , 
		  "CHGCD" VARCHAR(4) NOT NULL WITH DEFAULT '' , 
		  "CALCFLAG" DECIMAL(1,0) WITH DEFAULT 0 , 
		  "PERCENT" DECIMAL(6,3) WITH DEFAULT 0 , 
		  "CHGAMT" DECIMAL(10,3) WITH DEFAULT 0 , 
		  "MINCHGAMT" DECIMAL(10,3) WITH DEFAULT 0 , 
		  "MAXCHGAMT" DECIMAL(10,3) WITH DEFAULT 0 , 
		  "ACTIVE" DECIMAL(1,0) WITH DEFAULT 0 , 
		  "TSFIELD" VARCHAR(26) WITH DEFAULT '' , 
		  "CHGSWIFTCD" VARCHAR(3) NOT NULL WITH DEFAULT '' , 
		  "CREATEDBY" VARCHAR(10) , 
		  "CREATEDDT" DATE , 
		  "CREATEDTIME" TIME , 
		  "MODIFIEDBY" VARCHAR(10) , 
		  "MODIFIEDDT" DATE , 
		  "MODIFIEDTIME" TIME , 
		  "SPLFTVAL" VARCHAR(35) NOT NULL WITH DEFAULT '' , 
		  "RTGL" DECIMAL(1,0) NOT NULL WITH DEFAULT 0 , 
		  "PURPCODE" VARCHAR(50) NOT NULL WITH DEFAULT '' , 
		  "CLRSCHEMA" VARCHAR(35) )   
		 IN "STATDATA1SPACE" INDEX IN "STATINDX1SPACE" ;
ALTER TABLE "DB2INST1"."MPRODCHG" 
	ADD PRIMARY KEY
		("PRDCD",
		 "SWIFTCD",
		 "BNDCD",
		 "CHGCD",
		 "CHGSWIFTCD",
		 "SPLFTVAL",
		 "RTGL",
		 "PURPCODE");